vocab = {
    'zm': 'var',
    'stała': 'const',
    'funkcja': 'function',
    'zwróć': 'return',
    'generator': 'function*',
    'dostarcz': 'yield',
    'jeśli': 'if',
    'inaczej': 'else',
    'przez': 'for',
    'podczas': 'while',
    'dopóki': 'while',
    'tak': 'true',
    'nie': 'false',
    'prawda': 'true',
    'fałsz': 'false',
    'wyjdź': 'break',
    'jedź': 'continue',
    'kontynuuj': 'continue',
    'argumenty': 'arguments',
    'parametry': 'arguments',
    'przełącz': 'switch',
    'gdy': 'case',
    'domyślnie': 'default',
    'spróbuj': 'try',
    'złap': 'catch',
    'ostatecznie': 'finally',
    'finalnie': 'finally',
    'usuń': 'delete',
    'klasa': 'class',
    'interfejs': 'interface',
    'rozszerza': 'extends',
    'rzuca': 'throws',
    'rób': 'do',
    'zrób': 'do',
    'w': 'in',
    'z': 'with',
    'nowy': 'new',
    'nowa': 'new',
    'nowe': 'new'
};

module.exports = vocab;